"""Collect pollution readings from OpenAQ with CPCB and synthetic fallback."""

from __future__ import annotations

import logging
import os
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from src.common import (
    get_project_root,
    initialize_environment,
    safe_request_json,
)
from src.processing.data_validator import (
    impute_pollution_missing_values,
    validate_pollution_ranges,
)

LOGGER = logging.getLogger(__name__)

POLLUTANTS = ["pm25", "pm10", "co", "no2", "so2", "o3"]


def _load_factories(config: Dict[str, Any]) -> pd.DataFrame:
    """Load factory dataset generated by the ingestion layer.

    Args:
        config: Runtime configuration.

    Returns:
        pd.DataFrame: Factory dataset.
    """
    path = get_project_root() / config["paths"]["factories_raw"]
    if not path.exists():
        raise FileNotFoundError(f"Factory dataset not found at {path}")
    return pd.read_csv(path)


def _build_headers() -> Dict[str, str]:
    """Build OpenAQ request headers.

    Returns:
        Dict[str, str]: HTTP headers.
    """
    headers = {"accept": "application/json"}
    api_key = os.getenv("OPENAQ_API_KEY")
    if api_key:
        headers["X-API-Key"] = api_key
    return headers


def _fetch_openaq_locations(
    config: Dict[str, Any],
    latitude: float,
    longitude: float,
    radius_meters: int = 50000,
) -> List[Dict[str, Any]]:
    """Fetch nearby OpenAQ locations.

    Args:
        config: Runtime configuration.
        latitude: Query latitude.
        longitude: Query longitude.
        radius_meters: Search radius.

    Returns:
        List[Dict[str, Any]]: OpenAQ location objects.
    """
    ingestion_cfg = config["ingestion"]
    url = f"{config['apis']['openaq_url']}/locations"
    # OpenAQ v3 enforces radius <= 25000 meters.
    effective_radius = min(int(radius_meters), 25000)

    params = {
        "coordinates": f"{latitude},{longitude}",
        "radius": effective_radius,
        "limit": 25,
        "country": "IN",
    }
    payload = safe_request_json(
        method="GET",
        url=url,
        timeout=ingestion_cfg["timeout_seconds"],
        max_retries=ingestion_cfg["max_retries"],
        backoff_base_seconds=ingestion_cfg["backoff_base_seconds"],
        rate_limit_seconds=ingestion_cfg["rate_limit_seconds"],
        params=params,
        headers=_build_headers(),
    )
    if not payload:
        return []
    return payload.get("results", [])


def _parse_measurements(
    results: List[Dict[str, Any]],
    station_meta: Optional[Dict[str, Any]] = None,
) -> Dict[Tuple[str, str], Dict[str, float]]:
    """Parse OpenAQ measurements into station-timestamp pollutant matrix.

    Args:
        results: Raw measurement rows.

    Returns:
        Dict[Tuple[str, str], Dict[str, float]]: Parsed measurements.
    """
    parsed: Dict[Tuple[str, str], Dict[str, float]] = {}
    for row in results:
        parameter_raw = row.get("parameter")
        if isinstance(parameter_raw, dict):
            parameter = (parameter_raw.get("name") or "").lower()
        else:
            parameter = (parameter_raw or "").lower()
        if parameter not in POLLUTANTS:
            continue

        station_name = row.get("location") or (station_meta or {}).get("name", "Unknown Station")
        timestamp = row.get("date", {}).get("utc") or row.get("datetime", "")
        if not timestamp:
            period = row.get("period", {})
            timestamp = (
                period.get("datetimeFrom", {}).get("utc")
                or period.get("datetimeTo", {}).get("utc")
                or ""
            )
        if not timestamp:
            continue

        key = (station_name, timestamp)
        if key not in parsed:
            coordinates = row.get("coordinates") or (station_meta or {}).get("coordinates", {})
            country_value = row.get("country")
            if isinstance(country_value, dict):
                country_name = country_value.get("name", "India")
            elif country_value:
                country_name = str(country_value)
            elif station_meta and isinstance(station_meta.get("country"), dict):
                country_name = station_meta.get("country", {}).get("name", "India")
            else:
                country_name = "India"
            parsed[key] = {
                "station_name": station_name,
                "station_lat": float(coordinates.get("latitude", np.nan)),
                "station_lon": float(coordinates.get("longitude", np.nan)),
                "timestamp": timestamp,
                "city": row.get("city") or (station_meta or {}).get("locality") or "Unknown",
                "country": country_name,
            }
        value = row.get("value")
        parsed[key][parameter] = float(value) if value is not None else np.nan
    return parsed


def _fetch_station_measurements(
    config: Dict[str, Any],
    station: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """Fetch last 30-day measurements for one OpenAQ station.

    Args:
        config: Runtime configuration.
        station: OpenAQ location object.

    Returns:
        List[Dict[str, Any]]: Pollution rows.
    """
    ingestion_cfg = config["ingestion"]
    date_to = datetime.now(timezone.utc)
    date_from = date_to - timedelta(days=30)
    station_name = station.get("name", "Unknown Station")
    sensor_ids: List[int] = []
    seen_parameters = set()
    for sensor in station.get("sensors", []):
        sensor_id = sensor.get("id")
        parameter_name = (
            (sensor.get("parameter") or {}).get("name", "").lower()
        )
        if (
            sensor_id is None
            or parameter_name not in POLLUTANTS
            or parameter_name in seen_parameters
        ):
            continue
        seen_parameters.add(parameter_name)
        sensor_ids.append(int(sensor_id))
    if not sensor_ids:
        LOGGER.warning("No OpenAQ sensors found for station %s", station_name)
        return []

    raw_results: List[Dict[str, Any]] = []
    for sensor_id in sensor_ids:
        url = f"{config['apis']['openaq_url']}/sensors/{sensor_id}/measurements"
        params = {
            "date_from": date_from.isoformat(),
            "date_to": date_to.isoformat(),
            "limit": 1000,
            "sort": "desc",
        }
        payload = safe_request_json(
            method="GET",
            url=url,
            timeout=ingestion_cfg["timeout_seconds"],
            max_retries=ingestion_cfg["max_retries"],
            backoff_base_seconds=ingestion_cfg["backoff_base_seconds"],
            rate_limit_seconds=ingestion_cfg["rate_limit_seconds"],
            params=params,
            headers=_build_headers(),
        )
        if payload:
            raw_results.extend(payload.get("results", []))

    if not raw_results:
        LOGGER.warning("No OpenAQ measurements returned for station %s", station_name)
        return []

    parsed = _parse_measurements(raw_results, station_meta=station)
    rows: List[Dict[str, Any]] = []
    for values in parsed.values():
        pm25 = float(values.get("pm25", np.nan))
        pm10 = float(values.get("pm10", np.nan))
        aqi_index = float(np.nanmean([pm25, pm10])) if not np.isnan(pm25) or not np.isnan(pm10) else np.nan
        rows.append(
            {
                "pm25": values.get("pm25", np.nan),
                "pm10": values.get("pm10", np.nan),
                "co": values.get("co", np.nan),
                "no2": values.get("no2", np.nan),
                "so2": values.get("so2", np.nan),
                "o3": values.get("o3", np.nan),
                "aqi_index": aqi_index,
                "timestamp": values["timestamp"],
                "station_name": values["station_name"],
                "station_lat": values["station_lat"],
                "station_lon": values["station_lon"],
                "city": values["city"],
                "country": values["country"],
                "source": "openaq",
            }
        )
    return rows


def _fetch_pollution_from_openaq(
    config: Dict[str, Any],
    factories: pd.DataFrame,
) -> List[Dict[str, Any]]:
    """Fetch OpenAQ pollution readings around factory clusters.

    Args:
        config: Runtime configuration.
        factories: Factory dataset.

    Returns:
        List[Dict[str, Any]]: Pollution readings.
    """
    rows: List[Dict[str, Any]] = []
    grouped = factories.groupby("city", as_index=False).agg(
        latitude=("latitude", "mean"),
        longitude=("longitude", "mean"),
    )

    for _, city_row in grouped.iterrows():
        stations = _fetch_openaq_locations(
            config=config,
            latitude=float(city_row["latitude"]),
            longitude=float(city_row["longitude"]),
        )
        if not stations:
            LOGGER.warning("No OpenAQ stations found near %s", city_row["city"])
            continue

        for station in stations[:5]:
            station_rows = _fetch_station_measurements(
                config=config,
                station=station,
            )
            rows.extend(station_rows)

    LOGGER.info("Collected %s pollution rows from OpenAQ", len(rows))
    return rows


def _fetch_pollution_from_cpcb() -> List[Dict[str, Any]]:
    """Placeholder for CPCB source integration.

    Returns:
        List[Dict[str, Any]]: CPCB readings if available.
    """
    LOGGER.info(
        "CPCB source integration requires dataset download/authentication. Skipping by default."
    )
    return []


def _generate_synthetic_pollution(factories: pd.DataFrame, row_count: int = 500) -> List[Dict[str, Any]]:
    """Generate synthetic pollution readings as fallback.

    Args:
        factories: Factory dataset.
        row_count: Number of rows to generate.

    Returns:
        List[Dict[str, Any]]: Synthetic pollution rows.
    """
    rng = np.random.default_rng(42)
    now = datetime.now(timezone.utc)
    rows: List[Dict[str, Any]] = []
    for index in range(row_count):
        factory = factories.iloc[index % len(factories)]
        station_lat = float(factory["latitude"]) + rng.normal(0, 0.05)
        station_lon = float(factory["longitude"]) + rng.normal(0, 0.05)
        ts = (now - timedelta(hours=index % (24 * 30))).isoformat()
        pm25 = float(np.clip(rng.normal(95, 35), 5, 350))
        pm10 = float(np.clip(rng.normal(140, 45), 10, 500))
        co = float(np.clip(rng.normal(1.6, 0.8), 0.05, 15))
        no2 = float(np.clip(rng.normal(58, 20), 5, 250))
        so2 = float(np.clip(rng.normal(24, 10), 2, 120))
        o3 = float(np.clip(rng.normal(42, 15), 5, 180))
        aqi_index = float(np.mean([pm25, pm10]))
        rows.append(
            {
                "pm25": pm25,
                "pm10": pm10,
                "co": co,
                "no2": no2,
                "so2": so2,
                "o3": o3,
                "aqi_index": aqi_index,
                "timestamp": ts,
                "station_name": f"{factory['city']} Monitoring Station {(index % 8) + 1}",
                "station_lat": station_lat,
                "station_lon": station_lon,
                "city": factory["city"],
                "country": factory.get("country", "India"),
                "source": "synthetic",
            }
        )
    return rows


def _distance_to_nearest_factory(
    pollution_df: pd.DataFrame,
    factories_df: pd.DataFrame,
    threshold_km: float,
) -> pd.DataFrame:
    """Keep pollution rows that are within threshold of at least one factory.

    Args:
        pollution_df: Pollution readings.
        factories_df: Factory dataset.
        threshold_km: Maximum valid station-factory distance.

    Returns:
        pd.DataFrame: Filtered pollution dataframe.
    """
    if pollution_df.empty:
        return pollution_df

    def _min_haversine_to_candidates(
        station_lat: float,
        station_lon: float,
        candidate_lats: np.ndarray,
        candidate_lons: np.ndarray,
    ) -> float:
        if candidate_lats.size == 0:
            return float("inf")

        lat1 = np.radians(station_lat)
        lon1 = np.radians(station_lon)
        lat2 = np.radians(candidate_lats)
        lon2 = np.radians(candidate_lons)
        delta_lat = lat2 - lat1
        delta_lon = lon2 - lon1

        arc = np.sin(delta_lat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(delta_lon / 2) ** 2
        distances = 2 * 6371.0 * np.arctan2(np.sqrt(arc), np.sqrt(1 - arc))
        return float(np.min(distances))

    all_factory_lats = factories_df["latitude"].astype(float).to_numpy()
    all_factory_lons = factories_df["longitude"].astype(float).to_numpy()
    city_factories: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}
    for city_name, city_group in factories_df.groupby("city"):
        city_factories[str(city_name)] = (
            city_group["latitude"].astype(float).to_numpy(),
            city_group["longitude"].astype(float).to_numpy(),
        )

    distances: List[float] = []
    keep_mask: List[bool] = []

    for row in pollution_df.itertuples(index=False):
        station_lat = float(row.station_lat)
        station_lon = float(row.station_lon)
        city_key = str(getattr(row, "city", ""))
        candidate_lats, candidate_lons = city_factories.get(city_key, (all_factory_lats, all_factory_lons))

        nearest = _min_haversine_to_candidates(
            station_lat=station_lat,
            station_lon=station_lon,
            candidate_lats=candidate_lats,
            candidate_lons=candidate_lons,
        )
        distances.append(nearest)
        keep_mask.append(nearest <= threshold_km)

    filtered = pollution_df.copy()
    filtered["nearest_factory_distance_km"] = distances
    filtered = filtered.loc[keep_mask].reset_index(drop=True)
    LOGGER.info("Filtered pollution rows to %s within %.1f km", len(filtered), threshold_km)
    return filtered


def collect_pollution_data(config: Optional[Dict[str, Any]] = None) -> pd.DataFrame:
    """Collect pollution data and persist to raw data path.

    Args:
        config: Optional pre-loaded configuration.

    Returns:
        pd.DataFrame: Pollution dataset.
    """
    runtime_config = config or initialize_environment()
    factories = _load_factories(runtime_config)

    rows = _fetch_pollution_from_openaq(runtime_config, factories)
    if not rows:
        rows = _fetch_pollution_from_cpcb()

    if not rows:
        LOGGER.warning("No real pollution data available. Generating synthetic fallback dataset.")
        rows = _generate_synthetic_pollution(factories)

    pollution_df = pd.DataFrame(rows)
    if len(pollution_df) > 20000:
        LOGGER.info(
            "OpenAQ returned %s rows; downsampling to 20000 for stable runtime",
            len(pollution_df),
        )
        pollution_df = pollution_df.sample(n=20000, random_state=42).reset_index(drop=True)

    pollution_df["timestamp"] = pd.to_datetime(pollution_df["timestamp"], errors="coerce", utc=True)
    pollution_df = pollution_df.dropna(subset=["timestamp", "station_lat", "station_lon"])
    pollution_df = _distance_to_nearest_factory(
        pollution_df=pollution_df,
        factories_df=factories,
        threshold_km=float(runtime_config["validation"]["haversine_threshold_km"]),
    )
    pollution_df = validate_pollution_ranges(pollution_df, runtime_config["validation"])
    pollution_df = impute_pollution_missing_values(pollution_df)

    output_path = get_project_root() / runtime_config["paths"]["pollution_raw"]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pollution_df.to_csv(output_path, index=False)
    LOGGER.info("Pollution dataset written to %s with %s rows", output_path, len(pollution_df))
    return pollution_df


def main() -> None:
    """Run pollution data collection module standalone."""
    config = initialize_environment()
    collect_pollution_data(config)


if __name__ == "__main__":
    main()
